name: Build Cleanflight NAZE (Bluepill)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi make

    - name: Build NAZE
      run: make TARGET=NAZE
